### ISSUE TITLE
connection gets repeatedly closed

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX_DID_Finder_lib#25]
## Description
Even when there are no requests coming, it repeatedly closes and opens connection.
Then you get output like this:

`
INFO servicex-fab rucio_did_finder None Stack terminated due to StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
INFO servicex-fab rucio_did_finder None Closing transport socket and unlinking: state=2; <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.233.75.59', 60114)>
ERROR servicex-fab rucio_did_finder None Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
ERROR servicex-fab rucio_did_finder None Failed to connect to RabbitMQ. Giving Up after 13 tries
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/servicex_did_finder_lib/communication.py", line 197, in init_rabbit_mq
    _channel.start_consuming()
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')
`
This happen due to work being done in the main thread.
Here example how it should be done:
https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py

**Comment by BenGalewsky** [comment]
Fixed with migration to celery
